#!/usr/bin/env python
'''replay

Usage:
    replay all | hack
    replay (-h | --help | --version)

Options:
    -h, --help    show this help message and exit
    --version     prints program version and exit
'''

import sys
from docopt import docopt
from jinja2 import Environment, PackageLoader

from lib.mock import mock
from lib.replay import replay

if __name__ == "__main__":

    arguments = docopt(__doc__, version='replay 0.0.1')
    hack = arguments['hack']

    try:
        jinja_env = Environment(loader=PackageLoader('lib.mock'))
        m = mock()
        m.writeVarsFile(hack)
        playbook_file = m.writePlaybook(jinja_env)
        inventory_file = m.writeInventoryFile()

        replay().run(playbook_file, inventory_file)
    except Exception, e:
        print 'replay failed - %s' % e
        sys.exit(1)

    print 'replay success'
    sys.exit(0)
